// @ts-nocheck
"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, ChartNoAxesCombined, CheckCircle2, ChevronDown, ChevronRight, ClipboardPenLine, FileDown, GraduationCap, HomeIcon, LogOut, Search, Settings, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import styles from "./page.module.css";

type User={id:number;name:string;email:string;role:"staff"|"teacher";is_active:boolean};
type UserDetail={user:User;subjects:Subject[]};
type Student={id:number;student_number:string;name:string;kana?:string;course:string;grade_year:number;class_name:string;status:string;email?:string};
type Subject={id:number;code:string;name:string;year:number;term:string;course:string;class_name:string;teacher_id:number|null;teacher?:User;students?:Array<{id:number}>;attendance_weight:number;attitude_weight:number;assignment_weight:number;deadline?:string;is_finalized:boolean;finalized_at?:string};
type Grade={id:number;student_id:number;attendance_rate:number|null;attitude:number|null;assignment:number|null;score:number|null;evaluation:string|null;student:Student};
type ReportFilters={year:string;term:string;subject_id:string;student_id:string;course:string};
type View="home"|"students"|"review"|"grades"|"reports"|"settings"|"userDetail";
type CsvDraft={file:File;type:"students"|"users"|"subjects";headers:string[];rows:string[][]};
const API=process.env.NEXT_PUBLIC_API_URL??"http://127.0.0.1:8888/api";

function Icon({name}:{name:string}){const icons:Record<string,typeof HomeIcon>={home:HomeIcon,students:Users,review:ChartNoAxesCombined,grades:ClipboardPenLine,reports:FileDown,settings:Settings,calendar:CalendarDays,search:Search};const Component=icons[name]??GraduationCap;return <Component aria-hidden="true" strokeWidth={1.9}/>}

export default function Home(){
  const [token,setToken]=useState<string|null>(null),[user,setUser]=useState<User|null>(null),[view,setView]=useState<View>("grades"),[toast,setToast]=useState("");
  const [subjects,setSubjects]=useState<Subject[]>([]),[subject,setSubject]=useState<Subject|null>(null),[grades,setGrades]=useState<Grade[]>([]),[savedGrades,setSavedGrades]=useState<Grade[]>([]);
  const [students,setStudents]=useState<Student[]>([]),[users,setUsers]=useState<User[]>([]),[dashboard,setDashboard]=useState<Record<string,number>>({});
  const [history,setHistory]=useState<{student:Student;grades:Array<Grade&{subject:Subject}>}|null>(null);
  const [userDetail,setUserDetail]=useState<UserDetail|null>(null),[userDetailLoading,setUserDetailLoading]=useState(false),[userActionLoading,setUserActionLoading]=useState(false);
  const [loading,setLoading]=useState(false),[baseLoading,setBaseLoading]=useState(false),[search,setSearch]=useState(""),[weightOpen,setWeightOpen]=useState(false),[modal,setModal]=useState<"student"|"user"|"subject"|"assign"|null>(null),[csvErrors,setCsvErrors]=useState<Array<{line:number;field:string;reason:string}>>([]),[csvDraft,setCsvDraft]=useState<CsvDraft|null>(null),[csvRole,setCsvRole]=useState<"teacher"|"staff">("teacher"),[currentYear,setCurrentYear]=useState(2026);
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const dirty=JSON.stringify(grades)!==JSON.stringify(savedGrades);const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),3200)};
  const logout=useCallback(async(message?:string)=>{if(token)await fetch(`${API}/logout`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});localStorage.removeItem("sansun-token");setToken(null);setUser(null);setSubjects([]);setSubject(null);setGrades([]);setSavedGrades([]);setSearch("");setUserDetail(null);setBaseLoading(false);setView("grades");if(message)notify(message);},[token]);
  const api=useCallback(async(path:string,options:RequestInit={})=>{const response=await fetch(`${API}${path}`,{...options,headers:{Accept:"application/json",Authorization:`Bearer ${token}`,...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})}});if(response.status===401){await logout("セッションが終了しました。再度ログインしてください。");throw new Error("unauthorized");}const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(data.message||"処理に失敗しました。"),{data});return data;},[token,logout]);
  const loadBase=useCallback(async()=>{if(!token)return;setBaseLoading(true);setLoading(true);try{const [me,subs,dash]=await Promise.all([api("/me"),api("/subjects"),api("/dashboard")]);setUser(me);setSubjects(subs);setDashboard(dash);if(subs[0])await loadGrades(subs[0].id);else{setSubject(null);setGrades([]);setSavedGrades([])}setView(me.role==="teacher"?"grades":"review");}catch{}finally{setBaseLoading(false);setLoading(false)}},[token,api]);
  async function loadGrades(id:number){try{const data=await api(`/subjects/${id}/grades`);setSubject(data.subject);setCurrentYear(data.subject.year);setGrades(data.grades);setSavedGrades(data.grades);setWeightOpen(false);}catch(e){notify((e as Error).message)}}
  useEffect(()=>{const stored=localStorage.getItem("sansun-token");if(stored)setToken(stored)},[]);useEffect(()=>{if(token)loadBase()},[token]);
  useEffect(()=>{if(user?.role!=="teacher"||!subject||subject.year===currentYear)return;const next=subjects.find(item=>item.year===currentYear&&item.name===subject.name&&item.term===subject.term)||subjects.find(item=>item.year===currentYear&&item.term===subject.term)||subjects.find(item=>item.year===currentYear);if(next)loadGrades(next.id)},[currentYear,user?.role,subjects,subject?.year]);
  useEffect(()=>{if(!token)return;const reset=()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>logout("10分間操作がなかったため自動ログアウトしました。"),600000)};const events=["mousemove","keydown","click","scroll","touchstart"];events.forEach(e=>window.addEventListener(e,reset,{passive:true}));reset();return()=>{events.forEach(e=>window.removeEventListener(e,reset));if(timer.current)clearTimeout(timer.current)}},[token,logout]);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
  function navigate(next:View){if(dirty&&!window.confirm("未保存の変更があります。保存せずに移動しますか？"))return;setGrades(savedGrades);setView(next);if(next==="students"||next==="settings"||next==="reports")loadMasters();}
  async function loadMasters(){if(user?.role!=="staff")return;try{const [s,u,sub]=await Promise.all([api("/masters/students"),api("/masters/users"),api("/masters/subjects")]);setStudents(s);setUsers(u);setSubjects(sub);return {students:s,users:u,subjects:sub}}catch(e){notify((e as Error).message);return null}}
  async function loadUserDetail(userId:number,show=true){if(show)setUserDetailLoading(true);try{const data=await api(`/masters/users/${userId}`);setUserDetail(data);if(show)setView("userDetail");return data}catch(e){notify((e as Error).message);return null}finally{if(show)setUserDetailLoading(false)}}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setLoading(true);try{const r=await fetch(`${API}/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:f.get("email"),password:f.get("password")})});const data=await r.json();if(!r.ok)throw new Error(data.message);localStorage.setItem("sansun-token",data.token);setBaseLoading(true);setToken(data.token);setUser(data.user)}catch(e){notify((e as Error).message)}finally{setLoading(false)}}
  function editGrade(id:number,key:"attendance_rate"|"attitude"|"assignment",raw:string){setGrades(items=>items.map(item=>{if(item.id!==id)return item;const next={...item,[key]:raw===""?null:Number(raw)};if(!subject||next.attendance_rate===null||next.attitude===null||next.assignment===null)return{...next,score:null,evaluation:null};const score=Math.round(next.attendance_rate*subject.attendance_weight/100+next.attitude*10*subject.attitude_weight/100+next.assignment*10*subject.assignment_weight/100);return{...next,score,evaluation:score>=90?"秀":score>=80?"優":score>=70?"良":score>=60?"可":"不可"}}))}
  async function saveGrades(){if(!subject)return;setLoading(true);try{const data=await api(`/subjects/${subject.id}/grades`,{method:"PUT",body:JSON.stringify({grades:grades.map(g=>({id:g.id,attendance_rate:g.attendance_rate,attitude:g.attitude,assignment:g.assignment}))})});setGrades(data.grades);setSavedGrades(data.grades);notify("下書きを保存しました。")}catch(e){notify((e as Error).message)}finally{setLoading(false)}}
  async function saveWeights(){if(!subject)return;const values=[subject.attendance_weight,subject.attitude_weight,subject.assignment_weight],total=values.reduce((sum,value)=>sum+value,0);if(total!==100||values.some(value=>!Number.isInteger(value)||value<0||value>100)){notify("各項目を0〜100の整数で入力し、評価重みの合計を100%にしてください。");return}try{const data=await api(`/subjects/${subject.id}/weights`,{method:"PUT",body:JSON.stringify({attendance_weight:subject.attendance_weight,attitude_weight:subject.attitude_weight,assignment_weight:subject.assignment_weight})});setSubject(data.subject);setGrades(data.grades);setSavedGrades(data.grades);setWeightOpen(false);notify("評価重みを保存し、全成績を再計算しました。")}catch(e){notify((e as Error).message)}}
  async function changeFinalized(item:Subject){try{const data=await api(`/subjects/${item.id}/${item.is_finalized?"unfinalize":"finalize"}`,{method:"POST"});setSubjects(s=>s.map(x=>x.id===item.id?data.subject:x));if(subject?.id===item.id)setSubject(data.subject);notify(data.message)}catch(e){const err=e as Error&{data?:{missing?:string[]}};notify(err.data?.missing?`${err.message}（${err.data.missing.join("、")}）`:err.message)}}
  async function createMaster(type:"students"|"users"|"subjects",body:Record<string,unknown>){try{await api(`/masters/${type}`,{method:"POST",body:JSON.stringify(body)});setModal(null);await loadMasters();notify("登録しました。")}catch(e){notify((e as Error).message)}}
  async function approveUserRole(userId:number,role:"teacher"|"staff",name:string){const roleLabel=role==="teacher"?"講師":"専任職員";if(!window.confirm(`${name}さんを${roleLabel}として承認しますか？`))return;setUserActionLoading(true);try{const data=await api(`/masters/users/${userId}/role-approval`,{method:"POST",body:JSON.stringify({role})});await loadMasters();setUserDetail(current=>current?.user.id===userId?{...current,user:data.user}:current);notify(data.message||`${roleLabel}として承認しました。`)}catch(e){notify((e as Error).message)}finally{setUserActionLoading(false)}}
  async function sendUserPasswordReset(userId:number,name:string){if(!window.confirm(`${name}さんにパスワード再設定メールを送信しますか？`))return;setUserActionLoading(true);try{const data=await api(`/masters/users/${userId}/password-reset`,{method:"POST"});notify(data.message||"パスワード再設定用リンクをメールで送信しました。");await loadUserDetail(userId,false)}catch(e){notify((e as Error).message)}finally{setUserActionLoading(false)}}
  async function deleteUser(userId:number){if(!window.confirm("この利用者を削除しますか？"))return;try{await api(`/masters/users/${userId}`,{method:"DELETE"});await loadMasters();notify("利用者を削除しました。")}catch(e){notify((e as Error).message)}}
  async function importCsv(file:File,type:string){const text=await file.text();const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(line=>line.trim()!=="");const parse=(line:string)=>{const out:string[]=[];let cell="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){out.push(cell.trim());cell="";continue}cell+=c}out.push(cell.trim());return out};const rows=lines.map(parse);if(!rows.length){notify("CSVにデータがありません。");return}setCsvErrors([]);setCsvDraft({file,type:type as CsvDraft["type"],headers:rows[0],rows:rows.slice(1)});}
  async function confirmCsv(){if(!csvDraft)return;const body=new FormData();body.append("file",csvDraft.file);body.append("type",csvDraft.type);body.append("year",String(currentYear));if(csvDraft.type==="users")body.append("role",csvRole);setLoading(true);try{const data=await api("/csv/import",{method:"POST",body});setCsvErrors(data.errors||[]);notify(data.message||"CSVを取り込みました。");setCsvDraft(null);const refreshed=await loadMasters();if(!refreshed)notify("取り込み後の一覧更新に失敗しました。画面を再読み込みしてください。")}catch(e){const err=e as Error&{data?:{errors?:typeof csvErrors}};setCsvErrors(err.data?.errors||[]);notify(err.message)}finally{setLoading(false)}}
  async function saveAssignment(teacherId:number,studentIds:number[]){if(!subject)return;try{await api(`/subjects/${subject.id}/assign`,{method:"PUT",body:JSON.stringify({teacher_id:teacherId||null,student_ids:studentIds})});setModal(null);await loadMasters();await loadGrades(subject.id);notify("担当講師と履修学生を紐づけました。")}catch(e){notify((e as Error).message)}}
  async function download(kind:"csv"|"pdf",filters:ReportFilters){const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value)params.set(key,value)});try{const r=await fetch(`${API}/reports/${kind}?${params}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error((await r.json()).message);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`grades-${filters.year||"all"}.${kind}`;a.click();URL.revokeObjectURL(url);notify(`${kind.toUpperCase()}を出力しました。`)}catch(e){notify((e as Error).message)}}
  async function showHistory(student:Student){try{setHistory(await api(`/students/${student.id}/history`))}catch(e){notify((e as Error).message)}}
  const years=[...new Set(subjects.map(s=>s.year).concat([currentYear]))].sort((a,b)=>b-a);const visibleSubjects=user?.role==="teacher"?subjects:subjects.filter(s=>s.year===currentYear);const filtered=useMemo(()=>grades.filter(g=>!search||g.student.name.includes(search)||g.student.student_number.includes(search)),[grades,search]);const complete=grades.filter(g=>g.score!==null).length;
  if(!token||!user)return <Login onSubmit={login} loading={loading} toast={toast}/>;
  const nav: Array<[View,string,string]>=user.role==="staff"?[["students","students","学生管理"],["review","review","成績確認"],["reports","reports","PDF出力"],["settings","settings","設定"]]:[];
  return <div className={styles.app}><header className={styles.top}><div className={styles.logo}><GraduationCap aria-hidden="true"/>成績管理システム</div><div className={styles.account}><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className={styles.year}><Icon name="calendar"/><span>{currentYear}年度</span><ChevronDown className={styles.downIcon}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{years.map(year=><DropdownMenuItem key={year} onSelect={()=>setCurrentYear(year)}>{year}年度</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className={styles.accountTrigger}><div className={styles.avatar}>{user.name.slice(0,1)}</div><div><strong>{user.name}</strong><small>{user.role==="staff"?"専任職員":"講師"}</small></div><ChevronDown className={styles.downIcon}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{user.email}</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem className={styles.logoutItem} onSelect={()=>logout()}><LogOut/>ログアウト</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><nav className={styles.nav}>{nav.map(([id,icon,label])=><Button variant="ghost" key={id} className={view===id?styles.navActive:""} onClick={()=>navigate(id)}><Icon name={icon}/>{label}</Button>)}</nav>
  <main className={styles.page}>{user.role==="teacher"?<GradeView subject={subject} subjects={visibleSubjects} grades={filtered} allCount={grades.length} complete={complete} search={search} setSearch={setSearch} loadGrades={loadGrades} editGrade={editGrade} dirty={dirty} saveGrades={saveGrades} weightOpen={weightOpen} setWeightOpen={setWeightOpen} setSubject={setSubject} saveWeights={saveWeights} readonly={!!subject?.is_finalized} canFinalize={false} onFinalize={()=>{}} loading={loading||baseLoading}/>:<>{view==="review"&&<ReviewView subjects={visibleSubjects} loadGrades={loadGrades} current={subject} grades={filtered} search={search} setSearch={setSearch} staff changeFinalized={changeFinalized}/>} {view==="students"&&<StudentsView students={students} search={search} setSearch={setSearch} open={()=>setModal("student")} importCsv={importCsv} csvErrors={csvErrors} showHistory={showHistory}/>} {view==="reports"&&<ReportsView subjects={subjects} students={students} download={download}/>} {view==="settings"&&<SettingsView2 users={users} subjects={subjects} students={students} open={setModal} selectSubject={setSubject} importCsv={importCsv} openUserDetail={loadUserDetail} deleteUser={deleteUser} csvErrors={csvErrors}/>} {view==="userDetail"&&userDetail&&<UserDetailView detail={userDetail} back={()=>navigate("settings")} sendReset={sendUserPasswordReset} approveRole={approveUserRole} loading={userActionLoading||userDetailLoading}/>}</>}</main>
  {csvDraft&&<CsvImportModal draft={csvDraft} role={csvRole} setRole={setCsvRole} close={()=>setCsvDraft(null)} confirm={confirmCsv} loading={loading}/>} {modal==="assign"?<AssignmentModal close={()=>setModal(null)} users={users.map(account=>({...account,role:"teacher"}))} students={students} subject={subject} save={saveAssignment}/>:modal&&<MasterModal type={modal} close={()=>setModal(null)} create={createMaster} users={users} subject={subject} assign={()=>{}}/>} {history&&<HistoryModal data={history} close={()=>setHistory(null)}/>} {toast&&<div className={styles.toast}>{toast}</div>}</div>
}

function CsvImportModal({draft,role,setRole,close,confirm,loading}:{draft:CsvDraft;role:"teacher"|"staff";setRole:(role:"teacher"|"staff")=>void;close:()=>void;confirm:()=>void;loading:boolean}){const labels={students:"学生名簿",users:"講師・専任職員名簿",subjects:"科目一覧"};return <div className={styles.overlay}><section className={`${styles.modal} ${styles.csvModal}`}><button type="button" className={styles.close} onClick={close}>×</button><div className={styles.csvKicker}>CSV取り込みの確認</div><h2>{labels[draft.type]}</h2>{draft.type==="users"&&<div className={styles.roleChoice}><p>取り込む利用者の役割を選択してください</p><div><button type="button" className={role==="teacher"?styles.roleActive:""} onClick={()=>setRole("teacher")}>講師</button><button type="button" className={role==="staff"?styles.roleActive:""} onClick={()=>setRole("staff")}>専任職員</button></div></div>}<p className={styles.csvFileName}>{draft.file.name}・{draft.rows.length}件</p><p className={styles.csvHelp}>この内容で取り込みます。列名と先頭5行を確認してから実行してください。</p><div className={styles.csvTableWrap}><table><thead><tr>{draft.headers.map((h,i)=><th key={i}>{h||`列${i+1}`}</th>)}</tr></thead><tbody>{draft.rows.slice(0,5).map((row,i)=><tr key={i}>{draft.headers.map((_,j)=><td key={j}>{row[j]||""}</td>)}</tr>)}</tbody></table></div>{draft.rows.length>5&&<p className={styles.csvMore}>ほか {draft.rows.length-5}件</p>}<div className={styles.csvActions}><button type="button" className={styles.secondary} onClick={close}>キャンセル</button><button type="button" className={styles.primary} onClick={confirm} disabled={loading}>{loading?"取り込み中…":"この内容で取り込む"}</button></div></section></div>}

function Login({onSubmit,loading,toast}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;loading:boolean;toast:string}){const [reset,setReset]=useState(false);const [resetEmail,setResetEmail]=useState("");const [resetMessage,setResetMessage]=useState("");async function requestReset(e:FormEvent){e.preventDefault();setResetMessage("");const r=await fetch(`${API}/password/request-reset`,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify({email:resetEmail})});const data=await r.json();setResetMessage(data.message||"メールを確認してください。")}return <div className={styles.loginPage}><div className={styles.loginBrand}><b>S</b><h1>成績管理システム</h1><p>SANSUN学園</p></div><form className={styles.loginCard} onSubmit={onSubmit}><h2>ログイン</h2><p>学校から発行されたアカウントでログインしてください。</p><label>メールアドレス<input name="email" type="email" defaultValue="staff@sansun.test" required/></label><label>パスワード<input name="password" type="password" defaultValue="Staff123" required/></label><button disabled={loading}>{loading?"確認中…":"ログイン"}</button><button type="button" className={styles.linkButton} onClick={()=>setReset(!reset)}>パスワードを再設定する</button>{reset&&<div className={styles.resetBox}><label>登録メールアドレス<input type="email" value={resetEmail} onChange={e=>setResetEmail(e.target.value)} required/></label><button type="button" className={styles.secondary} onClick={requestReset}>再設定リンクを送信</button>{resetMessage&&<p>{resetMessage}</p>}</div>}<div className={styles.demo}><b>デモアカウント</b><span>専任：staff@sansun.test / Staff123</span><span>講師：teacher@sansun.test / Teacher123</span></div></form>{toast&&<div className={styles.toast}>{toast}</div>}</div>}

function PageTitle({title,action}:{title:string;action?:ReactNode}){return <div className={styles.pageTitle}><h1>{title}</h1><span>ホーム</span><ChevronRight aria-hidden="true"/><span>{title}</span>{action&&<div className={styles.pageTitleActions}>{action}</div>}</div>}
function HomeView({user,dashboard,subjects,openGrades}:{user:User;dashboard:Record<string,number>;subjects:Subject[];openGrades:(s:Subject)=>void}){return <><PageTitle title="ホーム"/><div className={styles.welcome}><div><span>2026年度</span><h2>{user.name}さん、お疲れさまです</h2><p>{user.role==="staff"?"全科目の入力状況と確定状況を確認できます。":"担当科目の成績入力を進めてください。"}</p></div><div className={styles.welcomeMark}>✓</div></div><div className={styles.stats}><Stat label="学生数" value={dashboard.students||0} unit="名"/><Stat label="講師数" value={dashboard.teachers||0} unit="名"/><Stat label="対象科目" value={dashboard.subjects||0} unit="科目"/><Stat label="確定済み" value={dashboard.completed||0} unit="科目"/></div><section className={styles.card}><div className={styles.cardHead}><div><h2>成績入力状況</h2><p>科目を選択して入力画面へ移動できます。</p></div></div><table><thead><tr><th>年度・学期</th><th>科目</th><th>クラス</th><th>担当講師</th><th>状態</th><th></th></tr></thead><tbody>{subjects.map(s=><tr key={s.id}><td>{s.year}年度 {s.term}</td><td><strong>{s.name}</strong></td><td>{s.class_name}</td><td>{s.teacher?.name||"未設定"}</td><td><Status finalized={s.is_finalized}/></td><td><button className={styles.textButton} onClick={()=>openGrades(s)}>開く ›</button></td></tr>)}</tbody></table></section></>}
function Stat({label,value,unit}:{label:string;value:number;unit:string}){return <div className={styles.stat}><span>{label}</span><strong>{value}<small>{unit}</small></strong></div>}
function Status({finalized}:{finalized:boolean}){return <span className={finalized?styles.finalized:styles.draft}>{finalized&&<CheckCircle2 aria-hidden="true"/>}{finalized?"確定済み":"入力期間中"}</span>}

function GradeView(p:{subject:Subject|null;subjects:Subject[];grades:Grade[];allCount:number;complete:number;search:string;setSearch:(s:string)=>void;loadGrades:(id:number)=>void;editGrade:(id:number,k:"attendance_rate"|"attitude"|"assignment",v:string)=>void;dirty:boolean;saveGrades:()=>void;weightOpen:boolean;setWeightOpen:(v:boolean)=>void;setSubject:(s:Subject)=>void;saveWeights:()=>void;readonly:boolean;canFinalize:boolean;onFinalize:()=>void;loading:boolean}){
  if(!p.subject&&p.loading)return <Empty title="科目を読み込んでいます…" description="担当科目を確認しています。"/>;
  if(!p.subject)return <Empty title={p.subjects.length?"科目を選択してください":"担当科目が登録されていません"} description={p.subjects.length?"表示する科目を選択してください。":"専任職員に担当科目の紐づけを依頼してください。"}/>;
  const s=p.subject;
  const years=[...new Set(p.subjects.map(item=>item.year))].sort((a,b)=>b-a);
  const yearSubjects=p.subjects.filter(item=>item.year===s.year);
  const terms=[...new Set(yearSubjects.map(item=>item.term))];
  const subjectOptions=yearSubjects.filter(item=>item.term===s.term);
  const weightValues=[s.attendance_weight,s.attitude_weight,s.assignment_weight];
  const weightTotal=weightValues.reduce((total,value)=>total+value,0);
  const weightValid=weightTotal===100&&weightValues.every(value=>Number.isInteger(value)&&value>=0&&value<=100);
  const changeYear=(year:number)=>{const exact=p.subjects.find(item=>item.year===year&&item.name===s.name&&item.term===s.term)||p.subjects.find(item=>item.year===year&&item.term===s.term)||p.subjects.find(item=>item.year===year);if(exact)p.loadGrades(exact.id)};
  const changeTerm=(term:string)=>{const exact=p.subjects.find(item=>item.year===s.year&&item.term===term&&item.name===s.name)||p.subjects.find(item=>item.year===s.year&&item.term===term);if(exact)p.loadGrades(exact.id)};
  return <div className={styles.teacherGradePage}>
    <PageTitle title="成績入力"/>
    <section className={styles.filterCard}>
      <label>年度<select value={s.year} onChange={e=>changeYear(Number(e.target.value))}>{years.map(value=><option value={value} key={value}>{value}年度</option>)}</select></label>
      <label>学期<select value={s.term} onChange={e=>changeTerm(e.target.value)}>{terms.map(value=><option key={value}>{value}</option>)}</select></label>
      <label>科目<select value={s.id} onChange={e=>p.loadGrades(Number(e.target.value))}>{subjectOptions.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
      <label className={styles.search}><Icon name="search"/><input value={p.search} onChange={e=>p.setSearch(e.target.value)} placeholder="学籍番号・氏名で検索"/></label>
      <button className={styles.primary} onClick={()=>p.loadGrades(s.id)}>表示する</button>
      <div className={styles.count}>入力済み <strong>{p.complete}</strong> / {p.allCount}名</div>
    </section>
    <div className={styles.weightBar}>
      <span>評価重み：出席率 {s.attendance_weight}%／授業態度 {s.attitude_weight}%／課題評価 {s.assignment_weight}%</span>
      {!p.readonly&&<button onClick={()=>p.setWeightOpen(!p.weightOpen)}>重みを変更</button>}
    </div>
    {p.weightOpen&&<section className={styles.weightEditor}>
      {([['attendance_weight','出席率'],['attitude_weight','授業態度'],['assignment_weight','課題評価']] as const).map(([k,l])=><label key={k}>{l}<input type="number" min="0" max="100" value={s[k]} onChange={e=>p.setSubject({...s,[k]:Number(e.target.value)})}/>%</label>)}
      <b className={weightValid?styles.weightValid:styles.weightInvalid}>合計 {weightTotal}% {!weightValid&&<small>（各項目0〜100の整数・合計100%にしてください）</small>}</b>
      <button onClick={p.saveWeights} disabled={!weightValid}>保存</button>
    </section>}
    <section className={styles.saveBar}><div>最終保存：{new Date().toLocaleString("ja-JP")} {p.dirty&&<span>未保存の変更があります</span>}</div><div><b>⚠ 確定後は編集できません</b>{!p.readonly&&<button className={styles.secondary} onClick={p.saveGrades}>下書き保存</button>}{p.canFinalize&&<button className={styles.primary} onClick={p.onFinalize} disabled={p.loading}>{s.is_finalized?"確定解除":"入力内容を確定"}</button>}</div></section>
    <section className={styles.gradeCard}><table>
      <thead><tr><th>学籍番号</th><th>氏名</th><th>出席率</th><th>授業態度</th><th>課題評価</th><th>総合成績</th><th>状態</th></tr></thead>
      <tbody>{p.grades.map(g=>{const missing=g.attendance_rate===null||g.attitude===null||g.assignment===null;return <tr key={g.id} className={missing?styles.missingRow:""}><td>{g.student.student_number}</td><td>{g.student.name}</td><td><input disabled={p.readonly} className={g.attendance_rate===null?styles.required:""} type="number" min="0" max="100" value={g.attendance_rate??""} placeholder="入力必須" onChange={e=>p.editGrade(g.id,"attendance_rate",e.target.value)}/><span>%</span></td><td><select disabled={p.readonly} value={g.attitude??""} onChange={e=>p.editGrade(g.id,"attitude",e.target.value)}><option value="">選択</option>{[1,2,3,4,5,6,7,8,9,10].map(v=><option key={v}>{v}</option>)}</select></td><td><select disabled={p.readonly} value={g.assignment??""} onChange={e=>p.editGrade(g.id,"assignment",e.target.value)}><option value="">選択</option>{[1,2,3,4,5,6,7,8,9,10].map(v=><option key={v}>{v}</option>)}</select></td><td><strong>{g.score!==null?`${g.score} / ${g.evaluation}`:"-"}</strong></td><td><span className={missing?styles.pending:styles.done}>{missing?"未入力":"入力済み"}</span></td></tr>})}</tbody>
    </table></section>
  </div>;
}

function ReviewView({subjects,loadGrades,current,grades,search,setSearch,staff,changeFinalized}:{subjects:Subject[];loadGrades:(id:number)=>void;current:Subject|null;grades:Grade[];search:string;setSearch:(s:string)=>void;staff:boolean;changeFinalized:(s:Subject)=>void}){return <><PageTitle title="成績確認"/><section className={styles.filterCard}><label>年度<select><option>2026年度</option><option>2025年度</option></select></label><label>学期<select><option>すべて</option><option>前期</option><option>後期</option></select></label><label>科目<select value={current?.id||""} onChange={e=>loadGrades(Number(e.target.value))}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}（{s.term}）</option>)}</select></label><label className={styles.search}><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="学籍番号・氏名"/></label></section><section className={styles.card}><div className={styles.cardHead}><div><h2>{current?.name||"科目を選択"}</h2><p>{current?.year}年度 {current?.term}・{current?.class_name}</p></div>{current&&staff&&<button className={current.is_finalized?styles.secondary:styles.primary} onClick={()=>changeFinalized(current)}>{current.is_finalized?"確定解除":"この科目を確定"}</button>}</div><table><thead><tr><th>学籍番号</th><th>氏名</th><th>出席率</th><th>授業態度</th><th>課題</th><th>総合点</th><th>評価</th></tr></thead><tbody>{grades.map(g=><tr key={g.id}><td>{g.student.student_number}</td><td>{g.student.name}</td><td>{g.attendance_rate??"-"}%</td><td>{g.attitude??"-"}</td><td>{g.assignment??"-"}</td><td>{g.score??"-"}</td><td><strong>{g.evaluation??"未入力"}</strong></td></tr>)}</tbody></table></section></>}

function StudentsView({students,search,setSearch,open,importCsv,csvErrors,showHistory}:{students:Student[];search:string;setSearch:(s:string)=>void;open:()=>void;importCsv:(f:File,t:string)=>void;csvErrors:Array<{line:number;field:string;reason:string}>;showHistory:(s:Student)=>void}){const list=students.filter(s=>s.name.includes(search)||s.student_number.includes(search));return <><PageTitle title="学生管理"/><section className={styles.actionBar}><label className={styles.search}><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="学籍番号・氏名で検索"/></label><label className={styles.fileButton}>CSV取込<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0],"students")}/></label><button className={styles.primary} onClick={open}>＋ 学生を登録</button></section><section className={styles.card}><table><thead><tr><th>学籍番号</th><th>氏名</th><th>ふりがな</th><th>学年・クラス</th><th>コース</th><th>状態</th><th></th></tr></thead><tbody>{list.map(s=><tr key={s.id}><td>{s.student_number}</td><td><strong>{s.name}</strong></td><td>{s.kana||"-"}</td><td>{s.grade_year}年 {s.class_name}</td><td>{s.course}</td><td><span className={styles.done}>{s.status}</span></td><td><button className={styles.textButton} onClick={()=>showHistory(s)}>成績履歴</button></td></tr>)}</tbody></table></section><CsvErrors errors={csvErrors}/></>}
function ReportsView({subjects,students,download}:{subjects:Subject[];students:Student[];download:(k:"csv"|"pdf",f:ReportFilters)=>void}){const [filters,setFilters]=useState<ReportFilters>({year:"2026",term:"",subject_id:"",student_id:"",course:""});const change=(key:keyof ReportFilters,value:string)=>setFilters(f=>({...f,[key]:value}));return <><PageTitle title="成績出力"/><section className={styles.reportCard}><div className={styles.reportIcon}>▧</div><h2>成績表を出力</h2><p>年度・学期・科目・クラスまたは学生を選び、CSV／印刷可能なPDFを出力します。</p><div className={styles.reportFilters}><label>年度<select value={filters.year} onChange={e=>change("year",e.target.value)}><option value="">すべて</option>{[...new Set(subjects.map(s=>s.year))].sort((a,b)=>b-a).map(y=><option key={y} value={y}>{y}年度</option>)}</select></label><label>学期<select value={filters.term} onChange={e=>change("term",e.target.value)}><option value="">すべて</option><option>前期</option><option>後期</option></select></label><label>科目<select value={filters.subject_id} onChange={e=>change("subject_id",e.target.value)}><option value="">すべて</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.name}・{s.term}</option>)}</select></label><label>コース<select value={filters.course} onChange={e=>change("course",e.target.value)}><option value="">すべて</option><option>システムエンジニア</option><option>Webデザイナー</option><option>共通</option></select></label><label>学生<select value={filters.student_id} onChange={e=>change("student_id",e.target.value)}><option value="">クラス全体</option>{students.map(s=><option value={s.id} key={s.id}>{s.student_number} {s.name}</option>)}</select></label></div><div className={styles.reportButtons}><button className={styles.secondary} onClick={()=>download("csv",filters)}>CSVを出力</button><button className={styles.primary} onClick={()=>download("pdf",filters)}>PDFを出力</button></div></section></>}
function SettingsView({users,subjects,students,open,selectSubject,importCsv,csvErrors}:{users:User[];subjects:Subject[];students:Student[];open:(m:"user"|"subject"|"assign")=>void;selectSubject:(s:Subject)=>void;importCsv:(f:File,t:string)=>void;csvErrors:Array<{line:number;field:string;reason:string}>}){return <><PageTitle title="設定"/><div className={styles.settingsGrid}><section className={styles.card}><div className={styles.cardHead}><div><h2>講師・専任職員</h2><p>{users.length}名登録</p></div><button className={styles.primary} onClick={()=>open("user")}>＋ 登録</button></div>{users.map(u=><div className={styles.listRow} key={u.id}><div className={styles.miniAvatar}>{u.name.slice(0,1)}</div><div><strong>{u.name}</strong><small>{u.email}</small></div><span>{u.role==="staff"?"専任職員":"講師"}</span></div>)}<label className={styles.fileButton}>利用者CSV取込<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0],"users")}/></label></section><section className={styles.card}><div className={styles.cardHead}><div><h2>科目・紐づけ管理</h2><p>{students.length}名の学生</p></div><button className={styles.primary} onClick={()=>open("subject")}>＋ 科目</button></div>{subjects.map(s=><div className={styles.listRow} key={s.id}><div><strong>{s.name}</strong><small>{s.year}年度 {s.term}・{s.teacher?.name||"担当未設定"}</small></div><button className={styles.textButton} onClick={()=>{selectSubject(s);open("assign")}}>紐づけ</button></div>)}<label className={styles.fileButton}>科目CSV取込<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0],"subjects")}/></label></section></div><CsvErrors errors={csvErrors}/></>}

function MasterModal({type,close,create,users,subject,assign}:{type:"student"|"user"|"subject"|"assign";close:()=>void;create:(t:"students"|"users"|"subjects",b:Record<string,unknown>)=>void;users:User[];subject:Subject|null;assign:(id:number)=>void}){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(type==="student")create("students",{...f,grade_year:Number(f.grade_year)});if(type==="user")create("users",f);if(type==="subject")create("subjects",{...f,year:Number(f.year),teacher_id:f.teacher_id?Number(f.teacher_id):null})};return <div className={styles.overlay}><form className={styles.modal} onSubmit={submit}><button type="button" className={styles.close} onClick={close}>×</button><h2>{type==="student"?"学生を登録":type==="user"?"利用者を登録":type==="subject"?"科目を登録":"担当・履修の紐づけ"}</h2>{type==="student"&&<><label>学籍番号<input name="student_number" required/></label><label>氏名<input name="name" required/></label><label>ふりがな<input name="kana"/></label><label>コース<select name="course"><option>システムエンジニア</option><option>Webデザイナー</option><option>共通</option></select></label><label>学年<select name="grade_year"><option>1</option><option>2</option><option>3</option></select></label><label>クラス<input name="class_name" defaultValue="1組"/></label><input type="hidden" name="status" value="在籍中"/></>}{type==="user"&&<><label>氏名<input name="name" required/></label><label>メール<input type="email" name="email" required/></label><label>役割<select name="role"><option value="teacher">講師</option><option value="staff">専任職員</option></select></label><label>初期パスワード<input name="password" defaultValue="Password123"/></label></>}{type==="subject"&&<><label>科目コード<input name="code" required/></label><label>科目名<input name="name" required/></label><label>年度<input name="year" type="number" defaultValue="2026"/></label><label>学期<select name="term"><option>前期</option><option>後期</option></select></label><label>コース<select name="course"><option>共通</option><option>システムエンジニア</option><option>Webデザイナー</option></select></label><label>クラス<input name="class_name" defaultValue="1組"/></label><label>担当講師<select name="teacher_id"><option value="">未設定</option>{users.filter(u=>u.role==="teacher").map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label></>}{type==="assign"?<><p>{subject?.name}に担当講師と全学生を紐づけます。</p><label>担当講師<select id="assignTeacher" defaultValue={subject?.teacher_id||""}>{users.filter(u=>u.role==="teacher").map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><button type="button" className={styles.primary} onClick={()=>assign(Number((document.getElementById("assignTeacher") as HTMLSelectElement).value))}>全学生を紐づける</button></>:<button className={styles.primary}>登録する</button>}</form></div>}
function HistoryModal({data,close}:{data:{student:Student;grades:Array<Grade&{subject:Subject}>};close:()=>void}){return <div className={styles.overlay}><section className={`${styles.modal} ${styles.historyModal}`}><button className={styles.close} onClick={close}>×</button><h2>{data.student.name}さんの成績履歴</h2><p>{data.student.student_number}・{data.student.course}</p><table><thead><tr><th>年度・学期</th><th>科目</th><th>出席率</th><th>総合点</th><th>評価</th></tr></thead><tbody>{data.grades.map(g=><tr key={g.id}><td>{g.subject.year}年度 {g.subject.term}</td><td>{g.subject.name}</td><td>{g.attendance_rate??"-"}%</td><td>{g.score??"-"}</td><td><strong>{g.evaluation??"未入力"}</strong></td></tr>)}</tbody></table></section></div>}
function CsvErrors({errors}:{errors:Array<{line:number;field:string;reason:string}>}){return errors.length?<section className={styles.errorBox}><h3>CSVエラー（該当行は取り込まれていません）</h3>{errors.map((e,i)=><p key={i}>{e.line}行目／{e.field}：{e.reason}</p>)}</section>:null}
function Empty({title,description}:{title:string;description:string}){return <div className={styles.empty}><strong>{title}</strong><p>{description}</p></div>}

function AssignmentModal({close,users,students,subject,save}:{close:()=>void;users:User[];students:Student[];subject:Subject|null;save:(teacherId:number,studentIds:number[])=>void}){const [teacherId,setTeacherId]=useState(subject?.teacher_id??0);const [selected,setSelected]=useState<number[]>(subject?.students?.map(student=>student.id)??[]);const [query,setQuery]=useState("");const visible=students.filter(student=>!query||student.name.includes(query)||student.student_number.includes(query));const toggle=(id:number)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);const selectRequired=()=>setSelected(students.filter(student=>subject?.course==="共通"||student.course===subject?.course).map(student=>student.id));return <div className={styles.overlay}><section className={`${styles.modal} ${styles.assignmentModal}`}><button type="button" className={styles.close} onClick={close}>×</button><div className={styles.csvKicker}>必須科目・履修学生の設定</div><h2>{subject?.name??"科目"}</h2><label>担当講師<select value={teacherId} onChange={event=>setTeacherId(Number(event.target.value))}><option value={0}>未設定</option>{users.filter(user=>user.role==="teacher").map(user=><option value={user.id} key={user.id}>{user.name}</option>)}</select></label><div className={styles.assignmentTools}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="学籍番号・氏名で検索"/><button type="button" className={styles.secondary} onClick={selectRequired}>対象専攻を全選択</button><button type="button" className={styles.textButton} onClick={()=>setSelected([])}>選択解除</button></div><p className={styles.assignmentCount}>{selected.length}名を選択中</p><div className={styles.studentPicker}>{visible.map(student=><label key={student.id} className={selected.includes(student.id)?styles.studentSelected:""}><input type="checkbox" checked={selected.includes(student.id)} onChange={()=>toggle(student.id)}/><span><strong>{student.name}</strong><small>{student.student_number}・{student.course}・{student.grade_year}年</small></span></label>)}</div><div className={styles.csvActions}><button type="button" className={styles.secondary} onClick={close}>キャンセル</button><button type="button" className={styles.primary} onClick={()=>save(teacherId,selected)}>紐づけを保存</button></div></section></div>}

function UserDetailView({detail,back,sendReset,approveRole,loading}:{detail:UserDetail;back:()=>void;sendReset:(id:number,name:string)=>void;approveRole:(id:number,role:"teacher"|"staff",name:string)=>void;loading:boolean}){const {user,subjects}=detail;const isTeacher=user.role==="teacher";const nextRoleLabel=isTeacher?"専任職員":"講師";const roleChangeLabel=isTeacher?"講師から専任職員に変更":"専任職員から講師に変更";return <><PageTitle title="講師・専任職員の詳細" action={<button className={styles.secondary} onClick={back}>一覧に戻る</button>}/><div className={styles.userDetailGrid}><section className={styles.card}><div className={styles.userProfile}><div className={styles.userProfileAvatar}>{user.name.slice(0,1)}</div><div><h2>{user.name}</h2><p>{user.email}</p></div><span className={user.is_active?styles.done:styles.pending}>{user.is_active?"利用中":"停止中"}</span></div><div className={styles.userRoleLabel}>{isTeacher?"講師":"専任職員"}</div><div className={styles.userDetailActions}><button className={styles.secondary} onClick={()=>sendReset(user.id,user.name)} disabled={loading}>パスワード再設定メールを送る</button><button className={styles.primary} onClick={()=>approveRole(user.id,isTeacher?"staff":"teacher",user.name)} disabled={loading}>{roleChangeLabel}</button></div><p className={styles.userDetailNote}>{nextRoleLabel}に変更すると、役割が切り替わります。再設定メールを送ると、登録メールアドレスに1時間有効のリンクが届きます。</p></section><section className={styles.card}><div className={styles.cardHead}><div><h2>担当科目</h2><p>{isTeacher?"この講師が担当している科目":"専任職員に割り当てられている科目"}</p></div><strong>{subjects.length}科目</strong></div>{subjects.length?<div className={styles.userSubjectList}>{subjects.map(item=><div className={styles.userSubjectRow} key={item.id}><div><strong>{item.name}</strong><small>{item.code}・{item.year}年度 {item.term}</small></div><span>{item.course}・{item.class_name}</span></div>)}</div>:<p className={styles.empty}>担当科目はありません。</p>}</section></div></>}

function SettingsView2({users,subjects,students,open,selectSubject,importCsv,openUserDetail,csvErrors}:{users:User[];subjects:Subject[];students:Student[];open:(m:"user"|"subject"|"assign")=>void;selectSubject:(s:Subject)=>void;importCsv:(f:File,t:string)=>void;openUserDetail:(id:number)=>void;csvErrors:Array<{line:number;field:string;reason:string}>}){return <><PageTitle title="設定"/><div className={styles.settingsGrid}><section className={styles.card}><div className={styles.cardHead}><div><h2>講師・専任職員</h2><p>{users.length}名登録</p></div><div className={styles.cardActions}><label className={styles.fileButton}>CSV取込<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0],"users")}/></label><button className={styles.primary} onClick={()=>open("user")}>＋ 登録</button></div></div>{users.map(u=><div className={styles.listRow} key={u.id}><div className={styles.miniAvatar}>{u.name.slice(0,1)}</div><div><strong>{u.name}</strong><small>{u.email}</small></div><span>{u.role==="staff"?"専任職員":"講師"}</span><button className={styles.textButton} onClick={()=>openUserDetail(u.id)}>詳細</button></div>)}</section><section className={styles.card}><div className={styles.cardHead}><div><h2>科目・紐づけ管理</h2><p>{students.length}名の学生</p></div><div className={styles.cardActions}><label className={styles.fileButton}>CSV取込<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0],"subjects")}/></label><button className={styles.primary} onClick={()=>open("subject")}>＋ 科目</button></div></div>{subjects.map(s=><div className={styles.listRow} key={s.id}><div><strong>{s.name}</strong><small>{s.year}年度 {s.term}・{s.teacher?.name||"担当未設定"}</small></div><button className={styles.textButton} onClick={()=>{selectSubject(s);open("assign")}}>紐づけ</button></div>)}</section></div><CsvErrors errors={csvErrors}/></>}
